"""add food_log_entries table

Revision ID: 8374a3d906e7
Revises: 4c21aae7bef6
Create Date: 2026-09-02 21:20:09.626420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8374a3d906e7'
down_revision: Union[str, Sequence[str], None] = '4c21aae7bef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('food_name_th', sa.String(length=200), nullable=False),
    sa.Column('serving_desc', sa.String(length=100), nullable=False),
    sa.Column('serving_g', sa.Float(), nullable=False),
    sa.Column('serving_kcal', sa.Float(), nullable=False),
    sa.Column('serving_protein_g', sa.Float(), nullable=False),
    sa.Column('serving_carb_g', sa.Float(), nullable=False),
    sa.Column('serving_fat_g', sa.Float(), nullable=False),
    sa.Column('quantity_servings', sa.Float(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("meal_type IN ('breakfast','lunch','dinner','snack')", name='ck_food_log_entries_meal_type'),
    sa.CheckConstraint('quantity_servings > 0', name='ck_food_log_entries_quantity_positive'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_log_entries_food_id'), 'food_log_entries', ['food_id'], unique=False)
    op.create_index('ix_food_log_entries_user_date', 'food_log_entries', ['user_id', 'logged_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_log_entries_user_date', table_name='food_log_entries')
    op.drop_index(op.f('ix_food_log_entries_food_id'), table_name='food_log_entries')
    op.drop_table('food_log_entries')
    # ### end Alembic commands ###
